plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs8.github.io/w19-mirza/
baseurl: "/w19-mirza"  

name: "CS 8 Winter 2019 Mirza"
course: "CS8"
course_title: "Introduction to Computer Science"
title: "UCSB CS8 W19 Mirza"
github_url: https://github.com/ucsb-cs8/w19-mirza
qtr: "W19"
quarter: "Winter 2019"
ta_names: "Mohith Pukale, Anacaren Ruiz"
lab_times: "Wednesdays: 9a, 10a, 11a, noon"
instructor: "Diba Mirza"
lecture_times: "TR 2:00p-3:15p"
lecture_location: "CHEM 1171"

class_org:
   name: ucsb-cs8-w19-mirza 
   url: https://github.com/ucsb-cs8-w19-mirza

start_week: 1
start_date: 2019-01-06 
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs8.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2019-01-07" },
  {"label":"Univ Holiday", "date":"2019-01-21" },
  {"label":"Drop deadline (no W grade)","date":"2019-02-04" },
  {"label":"Univ Holiday", "date":"2019-02-18" },
  {"label":"W19 Instruction Ends", "date":"2019-03-15" },  
  {"label":"W19 Quarter Ends", "date":"2019-03-22" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
